### ISSUE TITLE
Support Tailwind JIT

### ISSUE THREAD

**Issue by regisphilibert** [theNewDynamic/huge#43]
Pending this is addressed [upstream](https://github.com/gohugoio/hugo/issues/8343), we might take a 👀  at https://www.brycewray.com/posts/2021/11/making-tailwind-jit-work-hugo/ and see...

**Comment by brycewray** [comment]
> Pending this is addressed [upstream](https://github.com/gohugoio/hugo/issues/8343), we might take a 👀  at https://www.brycewray.com/posts/2021/11/making-tailwind-jit-work-hugo/ and see...

I surely know you'll do far better than I did, sir. ;-) The method I described therein is obviously and uncomfortably hacky.

**Comment by regisphilibert** [comment]
Well... Hugo Pipe PostCSS ability has not been updated for a long time, it's lacking a lot fo stuff compared to js.Build so I'm threading lightly. But we'll see :) I'll probably get back to you with questions :)

**Comment by regisphilibert** [comment]
I think we'll need two very different approaches. 1. Development and 2. Build

## Development

Tailwind has a CDN we can get (resourses.GetRemote). 

The doc mentions how you can add script tag with your tailwind config (we can get the file and print its content) along with a style tag
With your own tailwind powered styles (again get our file and print its content)

That should do it for development 

## build

We'll need to run two consecutive script

1. `npx tailwind` to build the tailwind css with tailwind config, template browsing etc...
2. Hugo. To take our own styles and concatenate then with the previously built tailwind css. 

Note that this is not necessarily ideal for Huge as this means users will need to run those scripts, adding them to their package.json scripts... we're getting away from the Hugo only approach. 

But this would allow us to use Tailwind 3 internally and forgo of PostCSS altogether. 

Until Hugo supports Tailwind JIT. (No eta in sight)

**Comment by brycewray** [comment]
Am presuming you already saw this (hence the "no eta in sight" mention):

https://discourse.gohugo.io/t/tailwind-v3-0-and-hugo/35994/9

**Comment by regisphilibert** [comment]
I did not! Thanks for pointing this out! This seems much closer than I initially thought. We'll wait for the upstream fix then, what I've got up there is quircky, time consuming, and wouldn't fit with what we're trying to achieve here: Simplify things.

**Comment by regisphilibert** [comment]
We've added it as an experimental feature pending the official upstream support!
