### ISSUE TITLE
huge/config/private/process/map" trigger a silent error on --watch

### ISSUE THREAD

**Issue by regisphilibert** [theNewDynamic/huge#44]
Currently on huge_sandbox (and AGNI), this line of code which looks for `...()` config functions prevents the site from rebuilding on save.

Need to investigage.

**Comment by regisphilibert** [comment]
It seems to be systematic when updating the `/layouts/index.html` file, but not necessarily others, though the problem did occur on others as well, just not systematically.

I was not able to find the difference between those repos. It seems only deleting the mention of the function works. Even wrapping it in false condition (`if false`) does not eliminate the problem. 

The next step is to setup a minimal repo and present it upstream,  but as I was unable to find the difference between thenewdynamic.com (no problem) and huge_sandbox (problem)

**Comment by darrenaddy** [comment]
Now that I'm getting a grasp on Hugo, I wanted to come back and see how Huge is getting along. I downloaded the basic version (I believe) but I don't even SEE a /layouts/index.html  The only thing in there are partials that contain "private" directories (a couple layers down). It looks like nothing has been done on this project in 7 months. Has it been abandoned?

**Comment by regisphilibert** [comment]
Hi @darrenaddy the project is pretty much alive, latest release is from a few weeks ago.
This issue should be close as it was related to #45

**Comment by darrenaddy** [comment]
Wow, thanks for the superfast reply! I must have somehow gotten on the wrong Github page (it was v0.1.3, which would explain why it wasn't updated from long ago). I'm pretty new to Github. :\  Glad to hear it is still alive. PS: thanks for all the great articles you've written either on your domain or thenewdynamic's. I had to find your Hugo Translator Cheatsheet in order to learn that printf is a concatenation function!

**Comment by darrenaddy** [comment]
I take it back. I followed the link from thenewdynamic.com page: https://www.thenewdynamic.com/article/introducing-huge-a-hugo-framework/
